### ISSUE TITLE
npm -i fails on concat-stream

### ISSUE THREAD

**Issue by kmjones1979** [linear-protocol/linear-subgraph#16]
I was trying to setup and test this subgraph but when I run `npm -i` I get the following error on a dependency...

```
1141 verbose stack Error: An unknown git error occurred
1141 verbose stack     at makeError (/Users/x/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
1141 verbose stack     at /Users/x/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
1142 verbose cwd /Users/x/projects/thegraph/linear-subgraph
1143 verbose Darwin 23.1.0
1144 verbose node v18.17.1
1145 verbose npm  v9.6.7
1146 error code 128
1147 error An unknown git error occurred
1148 error command git --no-replace-objects ls-remote ssh://git@github.com/hugomrdias/concat-stream.git
1149 error ERROR: Repository not found.
1149 error fatal: Could not read from remote repository.
1149 error
1149 error Please make sure you have the correct access rights
1149 error and the repository exists.
1150 verbose exit 128
```

**Comment by arkff202310** [comment]
Thanks for your report, we have upgrade the dependency, now you can install with `yarn`
